[project]
name = 'Auc-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Auction-contract]
path = 'contracts/Auction-contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.nft-contract]
path = 'contracts/nft-contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.payment-contract]
path = 'contracts/payment-contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.user-contract]
path = 'contracts/user-contract.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
