[project]
name = 'Auc-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Auction-contract]
path = 'contracts/Auction-contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.Nft-onwership]
path = 'contracts/Nft-onwership.clar'
clarity_version = 3
epoch = 3.0

[contracts.auction-completion]
path = 'contracts/auction-completion.clar'
clarity_version = 3
epoch = 3.0

[contracts.bidding-contract]
path = 'contracts/bidding-contract.clar'
clarity_version = 3
epoch = 3.0

[contracts.payment-contract]
path = 'contracts/payment-contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.user]
path = 'contracts/user.clar'
clarity_version = 3
epoch = 3.0

[contracts.user-contract]
path = 'contracts/user-contract.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
